source "https://rubygems.org"

ruby "2.6.1"

gem "sinatra"
gem "sinatra-contrib"
gem "erubis"
gem 'minitest'
gem 'minitest-reporters'
gem 'simplecov'
gem 'rack-test'
gem 'redcarpet'
gem 'bcrypt'
gem 'fileutils'

group :production do
  gem "puma"
end